editorial adjustments addressing #260, #261, #270, #271, and #276
yaronf/I-D pull request #287
Opened 2022-01-12 20:37 UTC by stpeter

2022-01-12 21:40 UTC, yaronf requested changes

2022-01-12 21:40 UTC, yaronf commented on BCP195bis/draft-ietf-uta-rfc7525bis.md
> +Transport Layer Security (TLS) and Datagram Transport Security Layer (DTLS) are widely used to protect data exchanged over application protocols such as HTTP, SMTP, IMAP, POP, SIP, and XMPP.  Over th
Maybe add that we have not update RFC 7457 for this revision of the BCP, instead we have included newly discovered attacks in the current document.

2022-01-12 21:40 UTC, yaronf commented on BCP195bis/draft-ietf-uta-rfc7525bis.md
> +- Detailed guidance was published on the use of TLS 1.2 {{!RFC5246}} and DTLS 1.2 {{!RFC6347}}, along with earlier protocol versions. This guidance is included in the original {{?RFC7525}} and mostly
Should we say that this guidance was largely adopted by the industry?

2022-01-13 10:50 UTC, thomas-fossati approved these changes
good stuff

2022-01-13 15:25 UTC, yaronf approved these changes

2022-01-13 15:25 UTC, merged