add to the changelog
yaronf/I-D pull request #470
Opened 2022-07-19 17:15 UTC by stpeter

Fixes https://github.com/yaronf/I-D/issues/467

2022-07-19 17:33 UTC, thomas-fossati requested changes

2022-07-19 17:33 UTC, thomas-fossati commented on BCP195bis/draft-ietf-uta-rfc7525bis.md
> +* Improved the text about Encrypted Client Hello.
this should go in a new "draft-ietf-uta-rfc7525bis-10" subsection.

2022-07-19 17:50 UTC, thomas-fossati approved these changes

2022-07-22 08:00 UTC, yaronf commented on BCP195bis/draft-ietf-uta-rfc7525bis.md
> +* Noted that these recommendations might apply to QUIC, but that QUIC is out of scope.
```suggestion
* Clarified applicability to QUIC.
```

I think the text is problematic (if they "might apply", how is the protocol out of scope). So let's be higher level here, and wrangle the exact text elsewhere.

2022-07-22 14:29 UTC, merged